services:
  speech:
    build: ./speech
    command: python speech.py
    volumes:
      - ./speech/:/app/

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:8000"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  notebooks:
    build: ./jupyter
    tty: true
    volumes:
      - ./jupyter/data/:/app/data
      - ./jupyter/notebooks/:/app/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
    env_file:
     - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root

  mazutalk:
    build: ./mazutalk
    depends_on:
      web:
        condition: service_healthy
    command: python mazutalk.py
    volumes:
      - ./mazutalk/:/app

  # db:
  #   image: postgres:16.2-alpine