services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mazuproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    image: nginx:1.25
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web

  certbot:
    image: certbot/certbot:v2.10.0
    volumes:
      - certbot_www:/var/www/certbot:rw
      - certbot_conf:/etc/letsencrypt:rw

volumes:
  static_volume:
  certbot_www:
  certbot_conf:
