# Generated by Django 5.0.4 on 2024-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
