# Generated by Django 5.0.4 on 2024-04-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='created',
            field=models.CharField(max_length=80),
        ),
    ]
