# Generated by Django 5.0.4 on 2024-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=80)),
                ('session_key', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
