# Generated by Django 5.0.4 on 2024-04-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0002_alter_prompt_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='created',
        ),
    ]
