# Generated by Django 5.0.4 on 2024-04-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0002_message_delete_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='prompt_text',
            new_name='prompt',
        ),
    ]
