# Generated by Django 5.0.4 on 2024-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0003_rename_prompt_text_message_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session_api_mazu',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
