# Generated by Django 5.0.4 on 2024-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0003_remove_prompt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='created',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
