# Generated by Django 5.0.4 on 2024-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0004_prompt_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest', models.BigIntegerField()),
            ],
        ),
    ]
