# Generated by Django 5.0.4 on 2024-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0005_remove_message_session_api_mazu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='last',
            name='last_object',
        ),
        migrations.AddField(
            model_name='last',
            name='last_prompt',
            field=models.BigIntegerField(default=0),
        ),
    ]
