# Generated by Django 5.0.4 on 2024-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0005_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='latest',
            field=models.BigIntegerField(default=0),
        ),
    ]
