# Generated by Django 5.0.4 on 2024-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0006_remove_last_last_object_last_last_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last',
            name='last_prompt',
            field=models.IntegerField(default=0),
        ),
    ]
