# Generated by Django 5.0.4 on 2024-04-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0007_alter_track_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='latest',
            field=models.BigIntegerField(),
        ),
    ]
