# Generated by Django 5.0.4 on 2024-04-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0008_alter_track_latest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
