# Generated by Django 5.0.4 on 2024-04-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0009_delete_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
