# Generated by Django 5.0.4 on 2024-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0010_alter_prompt_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent', models.DateTimeField()),
            ],
        ),
    ]
