# Generated by Django 5.0.4 on 2024-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0011_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='last',
            name='last_sent',
        ),
        migrations.AddField(
            model_name='last',
            name='last_object',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
