# Generated by Django 5.0.4 on 2024-04-17 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0013_alter_last_last_object_alter_prompt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 21, 26, 4, 64107)),
            preserve_default=False,
        ),
    ]
