# Generated by Django 5.0.4 on 2024-04-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0014_last_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='last',
            old_name='published',
            new_name='pub',
        ),
    ]
