# Generated by Django 5.0.4 on 2024-04-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazu', '0016_remove_last_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='created',
        ),
    ]
